name: Deploy to Firebase

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Update to the latest version of actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Update to the latest version of actions/setup-node
        with:
          node-version: '20' # Specify the Node.js version (20 is the latest as of now)

      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run deploy # Adjust this command if your deploy script is different
